name: CI Pipeline

on:
  push:
    branches:
      - main
      - master
      - tests
  pull_request:
    branches:
      - main
      - master
      - tests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Python installing
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt
          python -m spacy download en_core_web_sm

      - name: Unit tests run
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          coverage run -m pytest api/unit_tests1.py
          coverage xml -o coverage.xml

      - name: Integration tests run
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          coverage run -m pytest api/integration_tests.py
          coverage xml -o coverage.xml
